wavlake/catalog

app.yaml, staging.cloudbuild.yaml, staging.yaml
Switch to new staging db for staging deployments. Also added distinct staging and prod services config.
=> Add distinct deployment envs

controllers/albums.js, controllers/artists.js, controllers/tracks.ts, index.ts, library/db.ts, library/userHelper.js, middlewares/auth.js, middlewares/errorHandler.ts, package-lock.json, package.json, prod.cloudbuild.yaml, routes/albums.js, routes/artists.js, routes/tracks.js, staging.cloudbuild.yaml
Add basic CRUD routes for artists, albums, and tracks.
=> Import routes

controllers/albums.js, controllers/artists.js, controllers/tracks.ts
Add full object responses for artist, track, and album create and update routes.
Addresses #18
=> Improve create/update responses, error handling

controllers/tracks.ts, db/migrations/20230712171617_add_album_id_to_track_view.js, prisma/schema.prisma, prisma/views/public/TrackInfo.sql, routes/tracks.js
- Add track GETs for artist and album
- Update track info view (be sure to run `npm run migrate` and `npm run generate` to update db and prisma client)
=> Add track get routes

package.json, prod.cloudbuild.yaml, staging.cloudbuild.yaml
Getting build errors on GCP with node 18. Looks related to this: https://github.com/GoogleCloudPlatform/buildpacks/issues/198
=> Rollback node

controllers/stats.js, routes/stats.js
Fix the earnings and plays stats routes to fit FE data needs.
=> Update stats routes

prod.cloudbuild.yaml, staging.cloudbuild.yaml
Attempt to fix GCP build errors
=> Set node explicitly

package.json
=> Fix node version in package

controllers/albums.js, db/migrations/20230719222127_add_genre_to_albums.js, prisma/schema.prisma
Requires running `migrate` on db and `generate` for Prisma.
=> Add genre to albums table

controllers/albums.js, controllers/artists.js, library/cloudfrontClient.js, routes/artists.js
=> Fix artwork updating

controllers/tracks.ts, db/migrations/20230724203953_add_lyrics_and_refs.js, prisma/schema.prisma
Includes a db migration (run `migrate` and `generate`)
=> Add lyrics field to tracks, add userAgent for play logging

controllers/albums.js, controllers/artists.js, controllers/stats.js, controllers/tracks.ts, db/migrations/20230725162317_add_processing.js, db/migrations/20230725194658_update_track_view.js, library/s3Client.js, prisma/schema.prisma, prisma/views/public/TrackInfo.sql, routes/tracks.js
Includes 2 db migrations (requires `pull` and `generate`)
Also fix error handling
=> Add uploads through presigned url

controllers/tracks.ts, routes/tracks.js
Example over REST: `<catalog_url>/tracks?title=hello`
=> Add basic track search by title

controllers/artists.js, controllers/search.js, db/migrations/20230925212122_add-total-to-track-info.js, prisma/schema.prisma, prisma/views/public/TrackInfo.sql
Addresses #99 and #95
Includes migration.
=> Mobile fixes

controllers/accounts.ts, db/migrations/20231018140851_add_created_at_to_external_payments.js, library/db.ts, package-lock.json, package.json, prisma/schema.prisma, routes/accounts.js
Add history of user amps, combining both internal and external history. In order to accommodate both amps to a single recipient and split amps (to internal/external recipients), data is grouped by a `txId`. Example response:
```json
{
"success": true,
"data": {
"history": {
"f20e86f7-aea1-4cce-bff1-560a33d43925": [
{
"msatAmount": 118000,
"createdAt": "2023-10-18T14:52:09.174Z",
"title": "Sugar Baby (Single)",
"name": "Bobby Shell",
"fee": 0,
"txId": "f20e86f7-aea1-4cce-bff1-560a33d43925"
}
],
"b1f0f0ae-cf98-4e24-ae20-586b7456ab05": [
{
"msatAmount": 10000,
"createdAt": "2023-10-18T14:44:04.080Z",
"title": "Boostagram Ball",
"name": "Carol",
"fee": 0,
"txId": "b1f0f0ae-cf98-4e24-ae20-586b7456ab05"
},
{
"msatAmount": 20000,
"createdAt": "2023-10-18T14:44:04.079Z",
"title": "Boostagram …
```
=> Add user amp history endpoint

prod.yaml
=> Update memory in prod

controllers/artists.js, controllers/comments.ts, library/comments.ts, library/db.ts, prod.yaml
=> Include zap comments in artist results

controllers/artists.js, library/comments.ts, package-lock.json, package.json
=> Fix comment names, amounts

controllers/albums.js, controllers/comments.ts, middlewares/validatePagination.ts, package-lock.json, package.json, routes/comments.ts
since all of these comment controllers are essentially the same, just different IDs, i factored out the common code
=> Add album comments

library/podcastIndex/podcastIndex.ts
https://github.com/wavlake/catalog/assets/14062229/8f05e6ab-c897-4875-b85c-46ae29f18ebe
=> Add additional error handling around podcastindex API call

controllers/playlists.ts, routes/playlists.ts
Embed should be deployed to `main` once this is live: https://github.com/wavlake/embed/pull/30
=> Deployment 240311

controllers/charts.ts
Been seeing this particular query have severe performance issues the last day. This is a temp fix that should help improve performance while we determine root cause.
=> Hotfix: Update top query

services/rss/library/feedBuilder.ts
Will close https://github.com/wavlake/catalog/issues/376
=> Use podcast naemspace instead for music

controllers/episodes.ts, controllers/tracks.ts, library/s3Client.js
=> Delete from s3 on delete

controllers/accounts.ts, package-lock.json, package.json
`name` param is now optional on the route.
=> Add random username generator

controllers/promos.ts, db/migrations/20240919173302_promos.js, db/migrations/20240924143452_add_promo_to_track_view.js, index.ts, library/content.ts, library/promos.ts, prisma/schema.prisma, prisma/views/public/TrackInfo.sql, routes/promos.ts, services/accounting/controllers/promo.ts, services/accounting/index.ts, services/accounting/routes/promo.ts
Backed for promoted rewards system. Details at: https://www.notion.so/wavlake/Earn-v1-b19dea7b42084bd18c09893ba973a924
Postman project updated for reference in both accounting and catalog collections
=> Add promo endpoints

cronjobs/publish-feeds/index.ts
Also removes old date filter logic
=> Hotfix: Fix feed publishing with missing tracks/episodes

controllers/accounts.ts, controllers/meta.ts, routes/meta.ts
Add a new route and controller method to retrieve content type and metadata by content ID.
This change introduces the capability for the application to return detailed content information given a content ID, which is necessary for enhancing the app's functionality to better serve user requests by providing relevant content metadata. This approach optimizes content retrieval and aligns with planned feature expansions.
=> Add content type route

controllers/meta.ts
Add a new route to handle fetching content types, including input validation and additional error handling for invalid or non-existent content IDs.
Previously, there was no dedicated route for fetching content types which did not account for invalid content IDs. Adding a specific route with validation improves the robustness and reliability of the content ID handling, ensuring better error responses and user feedback. This allows for more precise retrieval and management of content types while preventing potential misuse.
=> Update content type route

controllers/accounts.ts, db/migrations/20250114110030_add_inbox_last_read.js, prisma/schema.prisma, routes/accounts.ts
Implement a filterable transaction retrieval system and add features for getting and updating the last read timestamp of user inboxes.
These changes enable users to fetch transactions based on specific filters to improve data retrieval efficiency and user experience. Additionally, storing and updating the last read timestamp for user inboxes allows the system to track which messages users have viewed, enhancing the usability of notification services. The approach uses existing database interactions and adds a new database field to accommodate the new inbox features comprehensively.
=> Deployment 250114 - inbox timestamp + tx filters

controllers/accounts.ts, library/queries/transactions.ts
Add a new `zapEvent` column to various query functions in `transactions.ts`, incorporating data from a left join with the `zap_request` table.
This change integrates the `zap_request` information into transaction-related queries, providing a more comprehensive view of transaction events by including potential zap events. The `zapEvent` field captures relevant events linked to transactions, allowing for enhanced tracking and auditing capabilities.
=> Add pubkey to txs

library/queries/transactions.ts
Remove the join with the `npub` table and add logic to conditionally return the `nostrPublicHex` based on `user_id` length in the `getEarningsDetail` function.
These changes simplify the query by removing an unnecessary join with the `npub` table and ensure that the `nostrPublicHex` is only included if the `user_id` represents a valid Nostr public key (64 characters long). This approach increases efficiency and clarity by dynamically checking the length of `user_id` rather than joining and returning metadata from a related table.
=> add nostr pubkey to getEarningsDetail

controllers/accounts.ts, library/zbd/zbdClient.ts
Introduce temporary console log statements in several functions within `accounts.ts` and `zbdClient.ts` to aid in debugging.
These changes are intended to troubleshoot and identify the root cause of specific issues by providing insight into the function's execution flow and potential failure points. The logs serve as a temporary debugging aid and will likely be removed or replaced with more permanent logging solutions once the issues are resolved.
=> Hotfix: add temp logs

controllers/accounts.ts, library/zbd/zbdClient.ts
Remove all console.log statements from the accounts and zbdClient controllers.
These logging statements were likely used for debugging purposes and are now unnecessary, potentially cluttering the console output and exposing sensitive information. Removing them ensures cleaner logs and improved application performance, avoiding accidental exposure of internal state data.
=> Hotfix: Revert logs

db/migrations/20250225115608_ticket_table.js, library/common.ts, library/constants.ts, library/deposit.ts, library/invoice.ts, library/nostr/common.ts, library/queries/transactions.ts, library/tickets.ts, library/zbd/responseInterfaces.ts, prisma/schema.prisma, services/accounting/controllers/invoice.ts, services/accounting/controllers/tickets.ts, services/accounting/index.ts, services/accounting/routes/tickets.ts
Add database schemas, routing, and logic for handling ticket sales and managing ticketed events in the application.
The introduction of ticket routes and corresponding database tables allows the platform to support events with ticket sales, enabling users to receive, verify, and manage payments for tickets. This addition addresses the need to integrate ticketed events into the existing financial transaction system, utilizing existing payment infrastructure while providing event-specific functionalities. The choice to extend existing enums and transaction handlers ensures compatibility and scalability within the current architecture.
=> Add ticket routes

db/migrations/20250225115608_ticket_table.js, db/migrations/20250227112832_add_pubkey_to_ticket.js, library/zap.ts, prisma/schema.prisma, services/accounting/controllers/callback.ts, services/accounting/controllers/tickets.ts
Add a "recipient_pubkey" field to the ticket model and database schema, improve error handling in zap request validation, and remove logging from the processIncomingKeysend function.
The introduction of the "recipient_pubkey" field supports better tracking of ticket recipients by their public keys, enhancing event processing accuracy. The error handling improvement in zap request validation streamlines error identification. Additionally, removing logging statements in `processIncomingKeysend` reduces unnecessary outputs in production environments.
=> Ticket route improvements

db/migrations/20250227141904_fix_ticket_schema.js, library/common.ts, library/deposit.ts, library/invoice.ts, prisma/schema.prisma, services/accounting/controllers/tickets.ts
Refactor the ticket processing logic by removing `external_receive_id` and related references, introducing `external_transaction_id` and `payment_request` fields, updating the database schema, and modifying related functions and types accordingly.
The existing system relied on `external_receive_id` for ticket processing, which was not ideal for the new payment system. This change aligns the ticket processing logic with the new transaction requirements by using `external_transaction_id` and `payment_request` for clearer and more efficient tracking of ticket transactions. This is necessary to accommodate updated business requirements and to optimize the ticketing system's integration with the payment infrastructure. 
> Is this description stale? Ask me to generate a new description by …
=> Fix ticket nostr col

library/deposit.ts, library/tickets.ts
Refactor ticket handling logic and enhance direct message (DM) functionality by incorporating encryption for secure transmission of ticket information to buyers.
The modifications aim to enhance the security and reliability of the ticketing system by ensuring sensitive information is only shared securely using encryption. Additionally, this update consolidates ticket update processes, improves user communication through personalized messages, and optimizes the use of shared resources (like the relay connection) for better performance.
=> refactor ticket handling and enhance DM functionality with encryption

db/migrations/20250225115608_ticket_table.js, library/deposit.ts, prisma/schema.prisma, services/accounting/controllers/tickets.ts
Add a `count` field to the ticket table, model, and relevant processes to account for multiple ticket purchases, and introduce validation to ensure ticket purchase constraints are followed.
This change addresses the need to handle scenarios where users can purchase multiple tickets at once, by adding a `count` field to track the quantity of tickets per transaction. The constraints implemented ensure adherence to event-specific limits on the maximum number of tickets available per person and overall, preventing over-purchasing and ensuring proper ticket distribution.
=> Add ticekt count

db/migrations/20250304103658_add_fiat_ticket_price.js, library/deposit.ts, library/invoice.ts, library/tickets.ts, prisma/schema.prisma, services/accounting/controllers/tickets.ts, services/nwc/library/method.ts
Implement checks for ticket count and amount for transactions, update schema and type mappings, handle internal payments accordingly, and perform code refactoring for consistency and clarity.
The changes address issues with handling transactions related to ticket purchases by ensuring that payment amounts are sufficient and that ticket counts are within allowed limits to prevent overselling. The changes also update the database schema and refactor variable names for consistency, facilitating easier maintenance and preventing potential errors in payment processing logic, especially for internal payments.
=> Add ticket count amount check

controllers/albums.js, controllers/tracks.ts
Implement checks to prevent the return of deleted content by modifying API endpoints related to albums, artists, and tracks in the backend services.
The aim is to ensure that deleted entities (albums, artists, tracks) are not retrievable or returned in API responses, thus improving data integrity and aligning with expected application behavior. This involves adding conditions to verify if an entity or its associated entities have been marked as deleted before proceeding with the response.
=> Dont return deleted content

services/accounting/routes/promo.ts
Comment out the `/reward` and `/create` promo endpoints in `promo.ts`.
To temporarily disable the promotion-related routes, likely to prevent their execution due to pending updates or issues that need resolution. Commenting out the code allows for easy reactivation in the future when those issues are addressed.
=> Disable promos

controllers/accounts.ts, library/queries/transactions.ts
…t transactions
Add functionality to retrieve detailed information for ticket transactions by implementing the `getTicketDetail` function and integrating it into the transaction handling logic.
These changes enable the system to correctly handle and provide details for ticket transactions, addressing the need for users to view and manage transaction-related information for events they have tickets for. The approach taken leverages existing transaction processing patterns, ensuring a consistent and maintainable codebase.
=> Handle ticket transaction detail

services/nwc/index.ts, services/nwc/library/heartbeat.ts, services/nwc/package.json
Implement health check functionality for the service and update service status management with new endpoints for basic and detailed status checks.
These changes introduce a health check server to monitor the service's operational status and relay connections, providing real-time health information and allowing for prompt detection of issues. The update aims to enhance system reliability and visibility into service health, addressing potential downtime proactively.
=> Feat: add NWC heartbeat

services/takedown/Dockerfile, services/takedown/cloudbuild.yaml, services/takedown/package-lock.json, services/takedown/package.json, services/takedown/src/index.ts, services/takedown/src/types.ts, services/takedown/tsconfig.json
Add a Dockerfile and build configuration for the takedown service, enabling request handling and a health check endpoint deployment on Cloud Run.
These changes establish a deployment pipeline for the new takedown service, which is essential for managing content removal requests. The Dockerfile sets the service environment, while the Cloud Build configuration ensures automated deployment, facilitating efficient scaling and management.
=> Add takedown service with request handling and health check endpoint

db/migrations/20250403121613_add_battery_promo_table.js, library/zbd/responseInterfaces.ts, library/zbd/zbdBatteryClient.ts, prisma/schema.prisma, services/accounting/.env.example, services/accounting/controllers/callback.ts, services/accounting/controllers/promo.ts, services/accounting/routes/callback.ts, services/accounting/routes/promo.ts
Add a new feature for handling battery promotional rewards, including the creation of `battery_reward` table, integrating new APIs through `zbdBatteryClient`, updating related controllers and routes to support battery reward processes for users, and extending the environment configuration for new API credentials.
This change allows the implementation of a new battery promotional reward system, providing a mechanism for distributing rewards to users based on microtransaction activities while ensuring comprehensive tracking and integration with existing systems. It introduces a robust backend solution leveraging third-party APIs, with the new modules facilitating seamless payment processing and reward management within the existing codebase.
> Is this description stale? Ask me to generate a …
=> Promo updates

library/zbd/responseInterfaces.ts, library/zbd/zbdBatteryClient.ts, library/zbd/zbdClient.ts, services/accounting/controllers/callback.ts, services/accounting/controllers/invoice.ts, services/accounting/controllers/promo.ts, services/accounting/routes/callback.ts, services/accounting/routes/promo.ts
Implement battery reward and static charge functionality, including database migrations, response types, API client, controllers, and routes.
These changes support the new battery reward feature, which involves implementing a system to manage rewards and static charges for user activities. This is achieved by setting up new database tables (`battery_reward` and `battery_balance`), creating relevant API response types, and adding new functions in `zbdBatteryClient` to handle API requests for creating and retrieving battery-related charges. The controllers and routes modifications facilitate the management and processing of battery rewards and static charges within the application.
> Is this description stale? Ask me to generate a new description by commenting …
=> Add static charge

db/migrations/20250407162144_add_invite_list.js, library/intake_invite_list_csv.ts, library/inviteList.ts, package-lock.json, package.json, prisma/schema.prisma, services/accounting/controllers/promo.ts
Implement invite list functionality by adding migrations, CSV import capability, invite list management, and integrate invite checks into promo controller logic.
The new invite list feature enables the management of invite lists, allowing for bulk import of emails from CSV files and the check of user eligibility for promotions based on their membership in specific invite lists. This change is necessary to streamline and automate the handling of invite lists, ensuring only invited users are eligible for certain rewards, aligning with the business requirement for controlled distribution of offers.
=> Add invite lists

db/migrations/20250408084952_add_battery_charge.js, library/zbd/responseInterfaces.ts, library/zbd/zbdBatteryClient.ts, prisma/schema.prisma, services/accounting/controllers/callback.ts, services/accounting/controllers/promo.ts, services/accounting/routes/callback.ts, services/accounting/routes/promo.ts
Update the battery invoice route by refactoring functions and endpoints related to 'static charge' to 'battery charge', simplifying request structure, adding `createInvoice` function, altering type definitions, and adjusting relevant route paths and handlers.
The changes are intended to enhance clarity and consistency in the naming conventions across the codebase, as well as improve the structure of invoice requests and responses. This shift from static descriptors to dynamic ones reflects the updated logic in handling battery invoices, aiming to streamline the process and reduce potential errors when processing invoice-related requests.
=> Update battery invoice route

controllers/charts.ts, routes/charts.js
Add a `get_beta_top_forty` endpoint in the charts controller to implement a more flexible and weighted scoring mechanism for retrieving the top 40 tracks, and update the router to include this new endpoint.
The addition of the `get_beta_top_forty` endpoint provides a more advanced and customizable way to calculate the top 40 tracks based on various weights and recency decay, reflecting user engagement and payments more accurately. This method allows for better experimentation and optimization of chart rankings. The new endpoint also supports custom time windows and score normalization to enhance flexibility in data analysis.
=> Beta top 40

controllers/charts.ts, routes/charts.js
Add a new `get_beta_top_forty` endpoint to calculate and retrieve a beta version of the Top 40 music chart with customizable parameters for scoring tracks.
This change provides enhanced chart functionality by allowing users to define scoring parameters such as time window, weights for various scoring factors, and whether to apply activity bonuses. This flexibility in scoring allows for a more tailored chart output matching specific user needs or testing scenarios.
=> Deployment 250421 - Beta top 40 algo

library/zap.ts, services/nwc/package-lock.json
Refactor the code structure in `zap.ts` for improved readability and maintainability by adding implementations of `makeZapRequest` and `makeZapReceipt` functions, along with related imports and clean-ups.
This refactor centralizes the logic for creating zap requests and receipts within the `zap.ts` file, reducing dependencies and improving code readability and maintainability by removing unused imports. The change also aligns with project goals of making the codebase more modular and easier to understand.
=> Refactor code structure for improved readability and maintainability

library/userHelper.ts
Add a condition to the `checkUserHasSufficientSats` function to include only withdrawals by checking if the "withdraw" flag is true.
To ensure that the balance check for a user accurately reflects pending withdrawals, enabling more precise calculations of available funds by excluding non-withdrawal transactions. This change is necessary to improve the accuracy of user balance computations, particularly when validating withdrawal transactions.
=> Add condition to check for withdrawals in checkUserHasSufficientSats

library/inviteList.ts
Refactor the `addUserToInviteList` function to use Prisma for database operations instead of the existing Knex-based implementation.
These changes aim to standardize database operations by fully transitioning to Prisma, which offers type-safe database access and simplifies handling unique constraints through the `upsert` method, replacing the previous implementation using Knex and a manual conflict resolution strategy. This transition also aligns with our ongoing effort to consolidate database interactions under a single ORM for improved code maintainability and readability.
=> Refactor addUserToInviteList to use Prisma for database operations

controllers/accounts.ts, db/migrations/20250512113648_add_pubkey_to_email_list.js, db/migrations/20250512115911_add_pubkey_to_battery_reward.js, library/inviteList.ts, library/promos.ts, library/zbd/zbdBatteryClient.ts, middlewares/nostrAuth.ts, prisma/schema.prisma, routes/accounts.ts, services/accounting/controllers/promo.ts, services/accounting/routes/promo.ts
Integrate Nostr authentication into the battery reward system and modify related database structures to support pubkey alongside Firebase UID for user identification.
These changes are implemented to enhance the authentication process by allowing Nostr events to authenticate requests, thereby providing more flexible user identification via either pubkey or Firebase UID. This supports cases where users may want to use Nostr for authentication instead of traditional methods. The database schema changes ensure compatibility with this dual-authentication approach and maintain data integrity by enforcing constraints that require at least one form of identification for invite lists and battery rewards.
> Is this description stale? Ask me to generate a new description by commenting …
=> Add nostr auth to battery

library/zap.ts
Add logging to the process of publishing a zap receipt to increase visibility and error tracing.
These changes are being made to improve the observability of zap receipt publishing events. Logging the zap request ID, the zap receipt event, publishing successes, and any potential errors ensures better tracking and debugging capabilities, which is useful for maintaining reliability and identifying issues quickly.
=> Deployment 250519 - Add Logging to Zap Receipt publishing

library/promos.ts
Refactor the `processBatteryReward` function to improve validation checks and transaction handling by wrapping validation and reward creation within a database transaction, adding detailed logging, and improving error handling.
The changes enhance data consistency and reliability by ensuring that all validations and the creation of reward records are treated as a single atomic transaction, which helps prevent concurrency issues and potential data corruption. The added logging and improved error messages provide better insights for debugging and monitoring, while ensuring edge cases, such as null values, are handled gracefully.
=> Improve battery rewards

db/migrations/20250711213804_fix_duplicate_forward_detail_payments.js
Create an archive table for duplicate records in `forward_detail`, remove duplicates while retaining the earliest record for each `external_payment_id`, and add a unique constraint, while implementing a rollback mechanism to restore duplicates if necessary.
The changes address issues with duplicate `forward_detail` records, which caused accounting discrepancies due to multiple payment callbacks for the same `external_payment_id`. The implemented solution ensures data integrity with a fallback mechanism for potential future reversions, improving both reliability and maintainability of the database schema.
=> Fix migration
